services:
  unifi:
    image: ghcr.io/linuxserver/unifi-network-application:10.1.85
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.37.1
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.32.4
  frigate: 
    image: ghcr.io/blakeblackshear/frigate:0.17.2
  jellyfin:  
    image: ghcr.io/jellyfin/jellyfin:10.11.11
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.22
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:0913501f5d05c019f5e3555a3299df1d8de420fdf882c92a8857787f9fbf999d
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0@sha256:2b2c1c05eb3f648d2c80dfab9486147dd7bb0ad4d77fa972fc1c5de8f1da3738
