services:
  unifi:
    image: ghcr.io/linuxserver/unifi-network-application:10.1.85
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.37.1
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.32.4
  frigate: 
    image: ghcr.io/blakeblackshear/frigate:0.17.2
  jellyfin:  
    image: ghcr.io/jellyfin/jellyfin:10.11.11
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.22
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:7356451f32395838628b241f33bcd7130df9302777fc23f80cbc7ca8b4997c02
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0@sha256:2b2c1c05eb3f648d2c80dfab9486147dd7bb0ad4d77fa972fc1c5de8f1da3738
