services:
  unifi:
    image: ghcr.io/linuxserver/unifi-network-application:10.1.85
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.37.3
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.33.2
  frigate: 
    image: ghcr.io/blakeblackshear/frigate:0.18.0
  jellyfin:  
    image: ghcr.io/jellyfin/jellyfin:10.11.11
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.22
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:4813745e2c721997d8849f5718786fd4406b3c656fbef479f87a161e51383cbd
  radarr:
    image: lscr.io/linuxserver/radarr:6.4.4@sha256:adb6c09d6b729ea5e642c99cea35af72702ef476bf4763f153299ac5db9f0b4f
