---
home-assistant: 
  image: ghcr.io/home-assistant/home-assistant:2024.5.0b1
esphome:
  image: ghcr.io/esphome/esphome:2024.4.1
immich:
  image: ghcr.io/immich-app/immich-server:v1.102.3
immich-ml:
  image: ghcr.io/immich-app/immich-machine-learning:v1.102.3
unifi:
  image: ghcr.io/linuxserver/unifi-network-application:8.1.113
vaultwarden:
  image: ghcr.io/dani-garcia/vaultwarden:1.30.5
deconz:
  image: ghcr.io/deconz-community/deconz-docker:2.26.3
frigate: 
  image: ghcr.io/blakeblackshear/frigate:stable
jellyfin:  
  image: ghcr.io/linuxserver/jellyfin:10.8.13
