apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  chart:
    spec:
      chart: nextcloud-aio-helm-chart
      version: 4.x
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      valuesFiles:
        - values.yaml
  install:
    remediation:
      retries: 3
  interval: 15m
  timeout: 5m
  releaseName: nextcloud
