---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-nextcloud-data
  labels:
    type: local
    tag: nextcloud-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/kube/nextcloud/data"
