---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath-nextcloud-postgresql
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      tag: nextcloud-database
