apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart: 7.1.238
    spec:
      chart: reflector
      version: 
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: reflector
  valuesFrom:
  - kind: ConfigMap
    name: reflector-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
