apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: default
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: false
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2024.3.0b3 # {"$imagepolicy": "flux-system:home-assistant"}  
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: host-volume
          mountPath: /config
        ports:
        - containerPort: 8123
      volumes:
      - name: host-volume
        persistentVolumeClaim:
          claimName: pvc-hostpath-home-assistant
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  namespace: default
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 8123
      name: web
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath-home-assistant
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      tag: ha-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-home-assistant
  namespace: default
  labels:
    type: local
    tag: ha-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/kube/home-assistant"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: default
# annotations:
#   cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - "*.thecullensnz.com"
    secretName: letsencrypt-wildcard-cert-thecullensnz.com
  rules:
  - host: "ha.thecullensnz.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-assistant-service
            port:
              number: 8123
