---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  chart:
    spec:
      chart: immich
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      version: 0.0.4
  interval: 15m
  timeout: 5m
  releaseName: immich
  values:
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            password: "thisshouldnotbeyourpassword"

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
  interval: 1m0s

