apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  chart:
    spec:
      chart: immich
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      version: 0.0.4
  interval: 15m
  timeout: 5m
  releaseName: immich
  values:
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: immich
            database: immich
            password: "thisshouldnotbeyourpassword"
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
    server:
      enabled: true
      env:
        NODE_ENV: "production"
      service:
        main:
          enabled: true
          primary: true
          type: ClusterIP
          ports:
            http:
              enabled: true
              primary: true
              port: 3001
              protocol: HTTP
      image:
        # -- image repository
        repository: altran1502/immich-server # {"$imagepolicy": "flux-system:immich-server:name"}
        # -- image tag
        tag: v1.53.0 # {"$imagepolicy": "flux-system:immich-server:tag"}
        # -- image pull policy
        pullPolicy: IfNotPresent
      command: "/bin/sh"
      args:
        - "./start-server.sh"
    ingress:
      main:
        enabled: true
        primary: false
        hosts:
          - host: photos.thecullensnz.com
            paths:
              - path: "/"
        tls:
          - hosts:
              - "*.thecullensnz.com"
            secretName: letsencrypt-wildcard-cert-thecullensnz.com
