apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: immich-machine-learning
  namespace: flux-system
spec:
  image: altran1502/immich-machine-learning
  interval: 1m0s
