apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: immich-machine-learning
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: immich-machine-learning
  policy:
    semver:
      range: ">=1.0.0 <2.0.0"
