---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-immich-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/kube/immich/data"
