---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-immich-postgresql
  labels:
    type: local
    tag: database
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/kube/immich/postgresql"
