---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath-immich-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
       storage: 10Gi
