---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-esphome-data
  labels:
    type: local
    tag: data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/kube/esphome/data"
