---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath-esphome-data
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
       storage: 10Gi
  selector: 
    matchLabels: 
      tag: data
