apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCcenZpjeDFs253eXtsn8vXkpAGXVUViI+hClGqKpCwD5+5i2TsUUg64jyJYcrahCEXX3wMrZeZrAzuPjuZ5YJCskMcs1Y45k8pZ71ihbZS/3cbCBt+sAivLkbllR4CCbg2OUs7IC2U77+2MiLP7nNdBialf6it9of9SutwftupJ+0INgJ1QGAv853rS8lWOTJ+Fd1jpn//fxfJK9+VQbVsT7Bk8YZ37UhbosEGvD1JCwGAlBTuny3OfTi6n/dE94lgNyxB8LzsynYRlMNIa1ynClr0unInStXXNwxjSJHRB8cfIeSVphTiNDKVVHSQRX2PxVKPTnjXtsr3+JRvxa10/OLmsu3GYGonh8rybsrPkXVsE0IC9m76Xhdp28scn7Z2plcP6Rn0H4eE0Gv/qVQPhup2NsjfTIKWic3GmyEbZ9sqFfnALO1+fKFsyxuNWiYFY1p3Fa0EPGnvvOW1zMNvHtjicLPcGwu4ihNKFKqMWZxe36qaxAdkviIq5KcwMp20PaWKd6IgOD9DaUy3TfZOwf+/3t7MRaAqW3cY1jLZ1f5IgtonAu/6wnkcnFw6FCuYBTMdXisl7GNwcCihtlQuc6YSQ5Bt3ql47TTQPHSP9Kh+tSrcjzvLnStKdxTCusqiFggqssVhHttG2gV2kUYD+g65mDjQKisX6Ha5SldC496zn/l5KgJS3ogsnezqFney+lnfREmAaP9bRbQEl7CHWvhdycBKccd81mYfTNEFWY1t9OfAjcWk
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

