name: Flux Auto-PR
on:
  create:
    branches: ['flux']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.event.commits[0].message }} into main"
        pr_body: " *An automated PR*"
        pr_reviewer: "jason-nz"
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
